### ISSUE TITLE
Calculated addresses from xpub do not match other wallets' calculated addresses

### ISSUE THREAD

**Issue by krupan** [Kimbatt/btc-address-generator#10]
I have generated a seed phrase using this tool and then taken the extended public key (xpub) and put it into Blue Wallet (https://bluewallet.io/).  I have then compared the calculated addresses that Blue Wallet and this tool give me and they do not match.

I have repeated this experiment with an xpub generated by my Trezor wallet.  I put the xpub from that into both this tool and Blue Wallet and the calculated addresses do not match (but they do match between Trezor and Blue Wallet).

Is this a bug?  Am I misunderstanding something?  I have checked the "Calculate hardened addresses?" box and that does not fix the problem.  I have generated up to 100 keys using this tool and still don't see a match.  I did make sure to to select bech32 addresses and I see that they all start with bc1q.

**Comment by Kimbatt** [comment]
Well, it's complicated. For example, let's use the following seed:
> inmate cargo cactus begin churn extend cluster bullet tone october ecology ghost minor enemy venture mercy opera unfair utility six problem gentle behind car

Selecting the Bech32 preset (using derivation path `m/84'/0'/0'`) gives us the following extended public key:
> zpub6sWe5bCHnKFzFu6ELFjK1Tx3cbCE4A12wKso6wXnHLevPXoqeG4vRWZymkPKuBkHj3u1zRpG2RFUz6dW3bq3UXLGST5foKyiMT36BnBrfzw

I used Electrum for testing, but I assume it's the same with Blue Wallet and Trezor. I created a new watch-only wallet using the zpub above. Electrum created the following addresses:
- Receiving:
  - bc1q3kev58ds53egdwgxhj0hajrxwazfuzp46m6nlv
  - bc1q9p04ve5pp32ks3d4vfrp42gh8nz5jsdu9d6mfs
  - bc1qja5et8q36hr6pz50wzstpfw0k3f3mv8r2mn8hc
  - etc.
- Change:
  - bc1qxp2mgmumx29c43quzmena68ldnv2xvrt83rgll
  - bc1q3yu23f0cczf20e903cfztuf6r85dh9jlg0atmk
  - etc.

Using this tool, the list of addresses is indeed different:
- bc1qfgt94yv64mudaw2sm9fupdzsr5337dzrdrm2mp
- bc1q2l89v9kudqpxrk972mg2g2sfwtgjpppj5ywna2
- etc.

This is because these addresses are generated from the path `m/84'/0'/0'`, so `m/84'/0'/0'/0`, `m/84'/0'/0'/1`, `m/84'/0'/0'/2`, etc.
Selecting Custom preset, and setting `m/0` (for receiving addresses) or `m/1` (for change addresses) will generate the correct addresses.
This is a bug, because using the Bech32 preset with the zpub above, it should actually generate the proper addresses (`m/0/0`,`m/0/1`, etc.).
(Also, after checking the `Calculate change addresses?` checkbox, the same addresses are generated)

**Comment by krupan** [comment]
OK, I think I understand.  For anyone following along, here's what you do:

Put your seed phrase into the Mnemonic Seed "Enter a seed phrase..." text entry field, click View details, then choose Bech32 as your preset and click Calculate addresses.  Then copy the extended key (public or private) and paste that into the Mnemonic Seed "Enter a seed phrase..." text entry field.  Click View details, then choose Custom as your preset and set the Derivation path to m/0 and click Calculate addresses.  Now you'll get the same addresses as other wallets.

This is the hierarchical part of hierarchical wallets, isn't it?  The m/84'/0'/0' that this tool uses for Bech32 is one "account" and so that's the base that wallets like Electrum and Trezor use to generate a series of addresses.

I think there is something wrong with Custom though, because if I calculate addresses with Bech32, it uses m/84'/0'/0' as the derivation path.  If I choose Custom and use that same derivation path, I get different addresses that don't even start with bc1.

**Comment by Kimbatt** [comment]
I fixed these issues:
The extended keys now show the account extended key (which is usually used by other wallets). For example, when using the Bech32 preset, the extended key will be `m/84'/0'/0'` (previously it was `m/84'/0'/0'/0` or `m/84'/0'/0'/1` for change addresses)
Added option to treat the entered key as root key
