### ISSUE TITLE
Doesn't work on raspberry pi

### ISSUE THREAD

**Issue by charltonh** [Kimbatt/btc-address-generator#2]
Tried with iceweasel and chromium on a raspberry pi 2 machine with 1GB RAM.

On Iceweasel:
ReferenceError: set_layout is not defined
SyntaxError: missing ; before statement   (index.html: 8616:28)

On Chromium:
Uncaught SyntaxError: Unexpected token )     (index.html: 7419)

The index.html file runs fine on my x86 machine, and I've confirmed using md5sum the file is the same on both machines.  I'm thinking it is possible it's erroring out due to memory constraints.  The SyntaxErrors all happen late in the code and the undefined functions are also defined late in the code.

**Comment by charltonh** [comment]
Update:  it does work using firefox-esr on raspberry pi.

No doubt this is environment related and not a bug in the code itself.  Perhaps once someone knows what's going on with this it could be documented somewhere.

**Comment by Kimbatt** [comment]
The syntax error on line 7419 is because the browser does not support [arrow functions](https://caniuse.com/#feat=arrow-functions), you can replace the line `window.setTimeout(() =>` with `window.setTimeout(function()`, but you need to replace all arrow functions then (so replace `() =>` with `function()` , and `(e) =>` with `function(e)`)
The error on line 8616 is because of the [let](https://caniuse.com/#feat=let) keyword, that part is required for the custom paper wallets, you can delete the entire block from line 8587 to line 8665, but then the custom image paper wallets won't work.

**Comment by charltonh** [comment]
Thank you very much for the info & input.  Yeah the browsers on RaspPi are very limited.  Probably only so much can be done, but at least it works with firefox.  I think chomium may be the most popular browser on the RaspPi platform though.
